#use_frameworks!
platform :ios, '8.0'

source 'https://github.com/Geph0rce/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'RFTypeface_Example' do
  pod 'RFTypeface', :path => '../'
  pod 'RFFoundation'
  pod 'Masonry'
  
  target 'RFTypeface_Tests' do
    inherit! :search_paths

    
  end
end
