#use_frameworks!
platform :ios, '8.0'

source 'https://github.com/Geph0rce/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'RFTypeface_Example' do
  pod 'RFTypeface', :path => '../'
  pod 'RFFoundation', :git => 'git@github.com:Geph0rce/RFFoundation.git', :branch => 'yaz'
  pod 'Masonry'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']

  target 'RFTypeface_Tests' do
    inherit! :search_paths

    
  end
end
